spring:
  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        # show formatted sql
        format_sql: true
        show_sql: true

app:
  auth:
    tokenSecret: aaabbbsdfsafd
    tokenExpirationMsec: 3600000 # 1 hour (in milliseconds)


server:
  servlet:
    session:
      timeout: 1800