spring:
  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        # show formatted sql
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dodakki123
    password: ruvfhfzmnrpvbwzq
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000

app:
  auth:
    tokenSecret: aaabbbsdfsafd
    tokenExpirationMsec: 3600000 # 1 hour (in milliseconds)

#server:
#  servlet:
#    session:
#      timeout: 1800